name: "AI PR Review (LM Studio / OpenAI)"
description: "Reviews PR diff using OpenAI-compatible Chat Completions (works with LM Studio and OpenAI cloud)."
author: "cumartesiolsun"
inputs:
  base_url:
    description: "OpenAI-compatible base URL (e.g. https://api.openai.com/v1 or http://host:11055/v1)"
    required: true
  api_key:
    description: "API key/token"
    required: true
  model:
    description: "Model name (e.g. openai/gpt-oss-20b or qwen3-coder)"
    required: true
  language:
    description: "Review language"
    required: false
    default: "Turkish"
  max_files:
    description: "Max files to review (avoid huge PRs)"
    required: false
    default: "25"
  max_chars:
    description: "Max diff chars total"
    required: false
    default: "120000"
  fail_on_issues:
    description: "If true, fail workflow when critical issues found"
    required: false
    default: "false"
  extra_instructions:
    description: "Extra reviewer instructions"
    required: false
    default: ""
  comment_marker:
    description: "Unique marker for sticky comments (use different values for multi-job setups)"
    required: false
    default: "AI_PR_REVIEW_ACTION"
  review_mode:
    description: "Review mode: 'summary' for single PR comment, 'inline' for per-file inline comments"
    required: false
    default: "summary"
  timeout_ms:
    description: "Request timeout in milliseconds for LLM calls"
    required: false
    default: "60000"
  max_tokens:
    description: "Max output tokens for LLM response"
    required: false
    default: "1024"
  chunk_size_chars:
    description: "Chunk size (chars) for splitting large diffs"
    required: false
    default: "12000"
  max_diff_chars_per_file:
    description: "Max diff chars per file before trimming"
    required: false
    default: "50000"
runs:
  using: "node20"
  main: "dist/index.js"